ZERO DIVSION 
result = 10 / 0 
print(result)
# Raises ZeroDivisionError

VALUE ERROR
num = int("abc")
# Raises ValueError

FILENOTFOUNDEDERROR
with open("nonexistent_file.txt", "r") as file:
        content = file.read()   # Raises FileNotFoundError

INDEX ERROR
my_list = [1, 2, 3]
value = my_list[1]  # No IndexError, within range
missing = my_list[5]  # Raises IndexError

KEY ERROR
my_dict = {"name": "Alice", "age": 30}
value = my_dict.get("city")  # No KeyError, using .get() method
missing = my_dict["city"]  # Raises KeyError

TYPE ERROR
result = "hello" + 5   
# Raises TypeError

ATTRIBUTE ERROR
text = "example"
length = len(text)  # No AttributeError, correct method usage
missing = text.some_method()  # Raises AttributeError

# using Try- except 
try:
    # Attempting to divide 10 by 0
    result = 10 / 0
except ZeroDivisionError:
    # Handling the ZeroDivisionError and printing an error message
    print("Error: Cannot divide by zero")
# This line will be executed regardless of whether an exception occurred
print("outside of try and except block")

a = 1

try:
    b = int(input("Please enter a number to divide a"))
    a = a/b
    print("Success a=",a)
except ZeroDivisionError:
    print("The number you provided cant divide 1 because it is 0")
except ValueError:
    print("You did not provide a number")
except:
    print("Something went wrong")
